In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
header = ['Game_ID', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18']

df = pd.read_csv('/mnt/Day_2_Input.txt', sep = ';|:|,', header = None, names = header)

df['Game_ID'] = df['Game_ID'].str.replace(r'Game ', '', regex=True).str.strip()

df

/tmp/ipykernel_413/4011694249.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df = pd.read_csv('/mnt/Day_2_Input.txt', sep = ';|:|,', header = None, names = header)

,Game_ID,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,1,14 green,8 blue,9 red,5 blue,4 green,2 red,4 red,4 blue,4 green,1 blue,3 green,2 red,10 red,3 blue,15 green,2 red,6 green,3 blue
1,2,1 red,12 green,2 blue,2 green,1 blue,1 red,4 green,2 blue,10 green,3 blue,4 green,2 red,2 blue,None,None,None,None,None
2,3,16 red,3 green,7 green,15 red,3 blue,4 green,20 red,1 blue,12 red,13 green,1 blue,2 green,8 red,1 blue,16 red,7 green,None,None
3,4,3 red,7 blue,4 blue,3 green,19 blue,1 red,3 green,16 blue,4 red,5 green,1 red,19 blue,3 green,None,None,None,None,None
4,5,7 blue,4 red,6 green,2 red,3 green,6 blue,11 blue,1 red,5 green,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,6 blue,5 green,6 red,3 red,5 blue,4 green,2 blue,2 red,3 green,None,None,None,None,None,None,None,None,None
96,97,3 red,8 green,2 blue,3 green,13 red,10 green,3 blue,None,None,None,None,None,None,None,None,None,None,None
97,98,4 green,9 red,2 blue,1 blue,5 green,18 red,3 green,16 red,15 red,1 green,2 blue,None,None,None,None,None,None,None
98,99,7 green,2 red,5 blue,9 red,17 green,19 blue,8 red,12 blue,1 green,11 red,11 green,10 blue,19 green,4 blue,2 red,None,None,None
99,100,4 blue,3 green,5 blue,12 green,16 green,1 red,1 blue,2 blue,1 green,1 red,3 blue,18 green,3 green,1 red,3 blue,None,None,None

### Part One

Which games are possible with 12 red cubes, 13 green cubes, and 14 blue cubes?

Maybe create 3 new columns, red_sum, blue_sum, and green_sum?

In [3]:
def red_max(row):
    red_values = [int(s) for value in row if 'red' in str(value) for s in str(value).split() if s.isdigit()]
    return np.max(red_values) if red_values else 0

def blue_max(row):
    blue_values = [int(s) for value in row if 'blue' in str(value) for s in str(value).split() if s.isdigit()]
    return np.max(blue_values) if blue_values else 0

def green_max(row):
    green_values = [int(s) for value in row if 'green' in str(value) for s in str(value).split() if s.isdigit()]
    return np.max(green_values) if green_values else 0

In [4]:
# Create new columns that pull out the max number of each color of cube
df['red_max'] = df.apply(red_max, axis = 1)
df['blue_max'] = df.apply(blue_max, axis = 1)
df['green_max'] = df.apply(green_max, axis = 1)

# Create conditions to apply to a filtered dataframe
red_condition = df['red_max'] <= 12
blue_condition = df['blue_max'] <= 14
green_condition = df['green_max'] <= 13

#Locate rows that satisfy all conditions and create a filtered df from it
filtered_df = df[red_condition & blue_condition & green_condition]

filtered_df

,Game_ID,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,red_max,blue_max,green_max
1,2,1 red,12 green,2 blue,2 green,1 blue,1 red,4 green,2 blue,10 green,...,2 red,2 blue,None,None,None,None,None,2,3,12
4,5,7 blue,4 red,6 green,2 red,3 green,6 blue,11 blue,1 red,5 green,...,None,None,None,None,None,None,None,4,11,6
5,6,7 red,13 blue,2 green,9 red,7 blue,7 green,3 red,12 blue,11 green,...,12 green,10 blue,None,None,None,None,None,9,13,12
11,12,13 green,2 red,2 blue,1 red,6 green,5 green,3 red,8 blue,None,...,None,None,None,None,None,None,None,3,8,13
12,13,2 blue,5 green,2 blue,2 green,2 blue,2 red,4 green,None,None,...,None,None,None,None,None,None,None,2,2,5
16,17,8 red,6 green,5 blue,7 green,10 red,6 blue,9 blue,10 green,7 red,...,5 blue,None,None,None,None,None,None,10,9,10
19,20,4 green,8 red,9 blue,6 blue,4 green,5 blue,7 green,9 red,9 red,...,None,None,None,None,None,None,None,9,9,7
20,21,1 green,11 red,2 blue,6 red,7 blue,5 red,1 green,2 red,7 blue,...,None,None,None,None,None,None,None,11,7,1
22,23,4 blue,12 red,1 green,1 green,10 blue,11 red,2 blue,1 blue,1 green,...,None,None,None,None,None,None,None,12,10,1
23,24,5 blue,1 green,2 green,2 blue,4 red,3 red,5 blue,None,None,...,None,None,None,None,None,None,None,4,5,2
27,28,6 blue,1 red,2 blue,1 red,1 red,1 green,5 blue,1 green,1 green,...,1 green,None,None,None,None,None,None,1,6,1
30,31,6 blue,7 green,4 red,8 green,6 blue,10 red,6 red,2 green,2 blue,...,6 red,2 red,7 green,7 red,13 green,2 blue,None,10,6,13
31,32,5 blue,2 green,8 blue,1 red,6 blue,2 green,2 green,11 blue,None,...,None,None,None,None,None,None,None,1,11,2
35,36,5 blue,3 red,2 green,3 red,9 green,6 red,1 blue,3 blue,4 red,...,None,None,None,None,None,None,None,6,5,9
36,37,14 blue,3 red,2 green,2 red,8 blue,11 blue,5 red,None,None,...,None,None,None,None,None,None,None,5,14,2
38,39,5 green,13 blue,1 red,6 green,1 red,12 blue,1 red,2 green,11 blue,...,12 blue,None,None,None,None,None,None,1,13,6
41,42,3 green,3 blue,1 red,2 red,8 blue,1 green,7 blue,2 red,1 green,...,None,None,None,None,None,None,None,2,8,3
42,43,8 green,10 red,4 blue,3 red,11 green,10 blue,4 red,5 blue,2 green,...,4 blue,None,None,None,None,None,None,10,10,11
45,46,9 blue,10 green,5 red,1 red,5 blue,1 green,6 blue,8 green,9 red,...,11 green,None,None,None,None,None,None,9,9,11
46,47,3 green,7 red,7 blue,12 red,1 blue,6 blue,4 green,6 red,6 red,...,None,None,None,None,None,None,None,12,7,4
49,50,6 blue,11 red,1 green,8 blue,11 red,5 blue,1 green,4 blue,12 red,...,6 red,8 blue,7 blue,5 red,None,None,None,12,8,1
50,51,5 red,7 green,8 green,4 blue,7 green,2 red,None,None,None,...,None,None,None,None,None,None,None,5,4,8
52,53,2 blue,1 green,4 red,12 blue,1 green,7 blue,4 red,8 blue,1 green,...,None,None,None,None,None,None,None,4,12,1
53,54,2 blue,7 green,1 red,1 green,2 blue,5 red,5 blue,7 green,5 red,...,7 green,7 green,2 blue,5 red,None,None,None,5,5,7
55,56,5 red,1 green,10 blue,2 red,1 blue,1 blue,2 red,1 green,8 blue,...,None,None,None,None,None,None,None,5,10,1
61,62,5 red,7 blue,13 green,7 green,6 blue,8 red,6 blue,8 red,12 green,...,5 red,4 blue,5 green,None,None,None,None,8,7,13
62,63,3 red,5 blue,2 red,10 red,1 green,4 blue,5 blue,4 red,3 green,...,None,None,None,None,None,None,None,10,5,3
63,64,7 blue,3 green,5 red,6 green,14 blue,1 green,12 blue,9 red,1 blue,...,None,None,None,None,None,None,None,9,14,12
64,65,12 red,12 blue,5 green,12 blue,11 red,6 green,3 red,14 blue,11 green,...,11 red,3 green,2 blue,13 blue,9 red,5 green,None,12,14,11
65,66,1 red,1 green,3 blue,6 red,3 green,6 blue,1 green,4 red,8 green,...,None,None,None,None,None,None,None,6,6,8
66,67,2 green,8 blue,5 red,7 blue,4 green,8 red,5 green,5 blue,2 red,...,None,None,None,None,None,None,None,8,8,5
69,70,10 blue,2 green,4 red,4 green,4 red,2 blue,7 green,5 red,1 blue,...,10 blue,7 green,2 blue,5 red,1 blue,9 red,2 green,9,10,7
70,71,1 green,6 blue,10 blue,2 red,1 green,8 blue,1 red,11 blue,2 green,...,10 blue,None,None,None,None,None,None,3,11,2
71,72,10 blue,3 red,2 green,11 red,4 green,3 blue,1 blue,4 red,3 green,...,None,None,None,None,None,None,None,11,10,4
73,74,5 green,4 blue,1 red,4 red,6 blue,2 red,2 blue,1 red,3 blue,...,None,None,None,None,None,None,None,4,6,5
77,78,5 blue,5 green,9 blue,2 green,5 red,4 red,4 blue,1 green,3 red,...,4 red,12 blue,3 green,4 green,5 red,13 blue,None,5,13,10
82,83,2 green,9 red,4 blue,3 green,4 blue,5 red,2 green,9 red,7 blue,...,None,None,None,None,None,None,None,9,7,3
85,86,4 red,1 green,14 blue,3 red,2 green,5 red,3 green,5 blue,13 blue,...,1 green,14 blue,3 red,None,None,None,None,5,14,11
86,87,1 blue,2 green,4 red,11 blue,3 green,4 red,11 blue,4 green,11 blue,...,5 green,2 red,None,None,None,None,None,4,11,5
87,88,1 red,1 blue,1 green,3 green,1 blue,1 red,9 blue,5 red,5 green,...,8 green,2 blue,3 red,13 green,8 blue,3 red,9 green,5,9,13
89,90,12 green,7 red,5 blue,12 green,1 blue,6 red,6 red,3 green,None,...,None,None,None,None,None,None,None,7,5,12
91,92,1 green,6 red,4 blue,5 blue,1 green,6 red,6 blue,None,None,...,None,None,None,None,None,None,None,6,6,1
93,94,11 red,1 green,1 blue,4 green,8 red,2 red,1 green,4 green,5 red,...,1 blue,2 green,9 red,None,None,None,None,11,1,4
95,96,6 blue,5 green,6 red,3 red,5 blue,4 green,2 blue,2 red,3 green,...,None,None,None,None,None,None,None,6,6,5

In [5]:
# Have to convert Game ID to int otherwise the summation doesn't work properly
filtered_df['Game_ID'] = pd.to_numeric(filtered_df['Game_ID'])

#Sum game IDs
part_1 = filtered_df['Game_ID'].sum()

print(part_1)

2256

/tmp/ipykernel_413/882568420.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['Game_ID'] = pd.to_numeric(filtered_df['Game_ID'])

### Part Two

For part 2, we need to find the minimimum number of each cube color per game, multiply those numbers together (create a new column) and then sum all of those numbers together.

In [6]:
df

,Game_ID,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,red_max,blue_max,green_max
0,1,14 green,8 blue,9 red,5 blue,4 green,2 red,4 red,4 blue,4 green,...,2 red,10 red,3 blue,15 green,2 red,6 green,3 blue,10,8,15
1,2,1 red,12 green,2 blue,2 green,1 blue,1 red,4 green,2 blue,10 green,...,2 red,2 blue,None,None,None,None,None,2,3,12
2,3,16 red,3 green,7 green,15 red,3 blue,4 green,20 red,1 blue,12 red,...,2 green,8 red,1 blue,16 red,7 green,None,None,20,3,13
3,4,3 red,7 blue,4 blue,3 green,19 blue,1 red,3 green,16 blue,4 red,...,19 blue,3 green,None,None,None,None,None,4,19,5
4,5,7 blue,4 red,6 green,2 red,3 green,6 blue,11 blue,1 red,5 green,...,None,None,None,None,None,None,None,4,11,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,6 blue,5 green,6 red,3 red,5 blue,4 green,2 blue,2 red,3 green,...,None,None,None,None,None,None,None,6,6,5
96,97,3 red,8 green,2 blue,3 green,13 red,10 green,3 blue,None,None,...,None,None,None,None,None,None,None,13,3,10
97,98,4 green,9 red,2 blue,1 blue,5 green,18 red,3 green,16 red,15 red,...,None,None,None,None,None,None,None,18,2,5
98,99,7 green,2 red,5 blue,9 red,17 green,19 blue,8 red,12 blue,1 green,...,10 blue,19 green,4 blue,2 red,None,None,None,11,19,19
99,100,4 blue,3 green,5 blue,12 green,16 green,1 red,1 blue,2 blue,1 green,...,18 green,3 green,1 red,3 blue,None,None,None,1,5,18

In [10]:
#Code was having issues trying to multiply all 3 columns together at the same time, so had to break it in to 2 different multiplications and columns
df['GB'] = np.multiply(df['blue_max'], df['green_max'])
df['Power'] = np.multiply(df['GB'], df['red_max'])

df

,Game_ID,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,red_max,blue_max,green_max,GB,Power
0,1,14 green,8 blue,9 red,5 blue,4 green,2 red,4 red,4 blue,4 green,...,3 blue,15 green,2 red,6 green,3 blue,10,8,15,120,1200
1,2,1 red,12 green,2 blue,2 green,1 blue,1 red,4 green,2 blue,10 green,...,None,None,None,None,None,2,3,12,36,72
2,3,16 red,3 green,7 green,15 red,3 blue,4 green,20 red,1 blue,12 red,...,1 blue,16 red,7 green,None,None,20,3,13,39,780
3,4,3 red,7 blue,4 blue,3 green,19 blue,1 red,3 green,16 blue,4 red,...,None,None,None,None,None,4,19,5,95,380
4,5,7 blue,4 red,6 green,2 red,3 green,6 blue,11 blue,1 red,5 green,...,None,None,None,None,None,4,11,6,66,264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,6 blue,5 green,6 red,3 red,5 blue,4 green,2 blue,2 red,3 green,...,None,None,None,None,None,6,6,5,30,180
96,97,3 red,8 green,2 blue,3 green,13 red,10 green,3 blue,None,None,...,None,None,None,None,None,13,3,10,30,390
97,98,4 green,9 red,2 blue,1 blue,5 green,18 red,3 green,16 red,15 red,...,None,None,None,None,None,18,2,5,10,180
98,99,7 green,2 red,5 blue,9 red,17 green,19 blue,8 red,12 blue,1 green,...,4 blue,2 red,None,None,None,11,19,19,361,3971
99,100,4 blue,3 green,5 blue,12 green,16 green,1 red,1 blue,2 blue,1 green,...,1 red,3 blue,None,None,None,1,5,18,90,90

In [11]:
part_2 = df['Power'].sum()

print(part_2)

74229